version: "0.1"
services:
    mongodb:
        container_name: mongo-dev
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - ~/yb/docker-volume/mongo:/data/db
        environment:
          - MONGO_INITDB_ROOT_USERNAME=admin
          - MONGO_INITDB_DATABASE=auth
          - MONGO_INITDB_ROOT_PASSWORD=pass
        networks: 
          - mongo-compose-network
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        ports:
            - 8081:8081
        environment:
          - ME_CONFIG_MONGODB_SERVER=mongo-dev
          - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
          - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
          - ME_CONFIG_BASICAUTH_USERNAME=admin
          - ME_CONFIG_BASICAUTH_PASSWORD=admin
        depends_on:
            - mongodb
        volumes:
            - ~/yb/docker-volume/mongo:/data/db
        networks: 
          - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge``